### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Pigmy-penguin**

### CODE REVIEW

**Comment by DeanoBurrito** [comment]
lgtm, thanks!

**Comment by dreamos82** [comment]
Thanks @Pigmy-penguin  :)

**Comment by Pigmy-penguin** [comment]
It didn't change in the file... Why? @dreamos82

**Comment by dreamos82** [comment]
i see all the changes in the master branch. There is only one /usr/share/consolefonts that needs to be fixed (if you have fixed it already but didn´t went in probably when the other pr was merged with master it was overwritten by it).

**Pull request merged**
